version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3001
    container_name: noted-app
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data:/app/data
      - ./backend/.env:/app/.env
    restart: always
    environment:
      - NODE_ENV=production