export const PRIORITIES = {
  URGENT: 'urgent',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
  BACKLOG: 'backlog',
  WORK: 'work',
  PERSONAL: 'personal'
};

export const PRIORITY_LIST = [
  PRIORITIES.URGENT,
  PRIORITIES.HIGH,
  PRIORITIES.MEDIUM,
  PRIORITIES.LOW,
  PRIORITIES.BACKLOG,
  PRIORITIES.WORK,
  PRIORITIES.PERSONAL
];

export const PRIORITY_COLORS = {
  [PRIORITIES.URGENT]: '#ef4444',
  [PRIORITIES.HIGH]: '#f87171',
  [PRIORITIES.MEDIUM]: '#fb923c',
  [PRIORITIES.LOW]: '#4ade80',
  [PRIORITIES.BACKLOG]: '#94a3b8',
  [PRIORITIES.WORK]: '#c047c2',
  [PRIORITIES.PERSONAL]: '#28d0d6'
};

export const PRIORITY_BG = {
  [PRIORITIES.URGENT]: 'rgba(239, 68, 68, 0.1)',
  [PRIORITIES.HIGH]: 'rgba(248, 113, 113, 0.1)',
  [PRIORITIES.MEDIUM]: 'rgba(251, 146, 60, 0.1)',
  [PRIORITIES.LOW]: 'rgba(74, 222, 128, 0.1)',
  [PRIORITIES.BACKLOG]: 'rgba(148, 163, 184, 0.1)',
  [PRIORITIES.WORK]: 'rgba(192, 71, 194, 0.1)',
  [PRIORITIES.PERSONAL]: 'rgba(40, 208, 214, 0.1)'
};
